/**
 * ASPプログラム設定
 * 5 ASP x 4 カテゴリ = 20 プログラム定義
 */

import type { AspProgram, AspName } from '@/types/asp-config'
import type { ContentCategory } from '@/types/content'

// ============================================================
// ASPプログラム一覧 (20エントリ)
// ============================================================

export const ASP_PROGRAMS: AspProgram[] = [
  // ── afb ──────────────────────────────────────────────
  {
    id: 'afb-aga-001',
    aspName: 'afb',
    programName: 'AGAスキンクリニック',
    programId: 'afb-prog-aga-001',
    category: 'aga',
    rewardTiers: [{ condition: '無料カウンセリング予約完了', amount: 15000, type: 'fixed' }],
    approvalRate: 72,
    epc: 85.5,
    itpSupport: true,
    cookieDuration: 60,
    isActive: true,
    recommendedAnchors: ['AGAスキンクリニック 公式サイト', 'AGA治療の無料カウンセリング', 'AGA治療を始める'],
  },
  {
    id: 'afb-hair-001',
    aspName: 'afb',
    programName: 'メンズリゼクリニック',
    programId: 'afb-prog-hair-001',
    category: 'hair-removal',
    rewardTiers: [{ condition: '無料カウンセリング予約完了', amount: 20000, type: 'fixed' }],
    approvalRate: 68,
    epc: 92.3,
    itpSupport: true,
    cookieDuration: 60,
    isActive: true,
    recommendedAnchors: ['メンズリゼ 公式サイト', 'メンズ脱毛の無料カウンセリング', '医療脱毛を始める'],
  },
  {
    id: 'afb-skin-001',
    aspName: 'afb',
    programName: 'ゴリラクリニック スキンケア',
    programId: 'afb-prog-skin-001',
    category: 'skincare',
    rewardTiers: [{ condition: '初回トライアル申込完了', amount: 8000, type: 'fixed' }],
    approvalRate: 75,
    epc: 45.2,
    itpSupport: true,
    cookieDuration: 45,
    isActive: true,
    recommendedAnchors: ['ゴリラクリニック スキンケア', 'メンズ美肌治療', '肌悩みを相談する'],
  },
  {
    id: 'afb-ed-001',
    aspName: 'afb',
    programName: 'クリニックフォア ED',
    programId: 'afb-prog-ed-001',
    category: 'ed',
    rewardTiers: [{ condition: 'オンライン診療予約完了', amount: 10000, type: 'fixed' }],
    approvalRate: 80,
    epc: 62.8,
    itpSupport: true,
    cookieDuration: 30,
    isActive: true,
    recommendedAnchors: ['クリニックフォア ED治療', 'オンラインED診療', 'ED治療の相談をする'],
  },

  // ── a8 ──────────────────────────────────────────────
  {
    id: 'a8-aga-001',
    aspName: 'a8',
    programName: 'Dクリニック',
    programId: 'a8-prog-aga-001',
    category: 'aga',
    rewardTiers: [{ condition: '無料カウンセリング予約完了', amount: 12000, type: 'fixed' }],
    approvalRate: 65,
    epc: 70.2,
    itpSupport: false,
    cookieDuration: 30,
    isActive: true,
    recommendedAnchors: ['Dクリニック 公式サイト', '薄毛治療の専門医に相談', 'AGA治療実績No.1クリニック'],
  },
  {
    id: 'a8-hair-001',
    aspName: 'a8',
    programName: 'レジーナクリニック オム',
    programId: 'a8-prog-hair-001',
    category: 'hair-removal',
    rewardTiers: [{ condition: '無料カウンセリング予約完了', amount: 18000, type: 'fixed' }],
    approvalRate: 70,
    epc: 78.6,
    itpSupport: false,
    cookieDuration: 30,
    isActive: true,
    recommendedAnchors: ['レジーナクリニック オム', 'メンズ医療脱毛', '男性脱毛の相談をする'],
  },
  {
    id: 'a8-skin-001',
    aspName: 'a8',
    programName: 'メンズスキンケア BULK HOMME',
    programId: 'a8-prog-skin-001',
    category: 'skincare',
    rewardTiers: [{ condition: '初回購入完了', amount: 5000, type: 'fixed' }],
    approvalRate: 82,
    epc: 38.4,
    itpSupport: false,
    cookieDuration: 45,
    isActive: true,
    recommendedAnchors: ['BULK HOMME 公式サイト', 'メンズスキンケアを始める', '男性用基礎化粧品'],
  },
  {
    id: 'a8-ed-001',
    aspName: 'a8',
    programName: 'DMMオンラインクリニック ED',
    programId: 'a8-prog-ed-001',
    category: 'ed',
    rewardTiers: [{ condition: 'オンライン診療予約完了', amount: 8000, type: 'fixed' }],
    approvalRate: 78,
    epc: 55.1,
    itpSupport: false,
    cookieDuration: 30,
    isActive: true,
    recommendedAnchors: ['DMMオンラインクリニック', 'オンラインED診療', 'ED薬のオンライン処方'],
  },

  // ── accesstrade ──────────────────────────────────────
  {
    id: 'at-aga-001',
    aspName: 'accesstrade',
    programName: '銀座総合美容クリニック AGA',
    programId: 'at-prog-aga-001',
    category: 'aga',
    rewardTiers: [{ condition: '無料相談予約完了', amount: 18000, type: 'fixed' }],
    approvalRate: 60,
    epc: 95.0,
    itpSupport: true,
    cookieDuration: 45,
    isActive: true,
    recommendedAnchors: ['銀座総合美容クリニック', 'AGA治療の専門院', '薄毛治療の無料相談'],
  },
  {
    id: 'at-hair-001',
    aspName: 'accesstrade',
    programName: 'メンズエミナルクリニック',
    programId: 'at-prog-hair-001',
    category: 'hair-removal',
    rewardTiers: [{ condition: '無料カウンセリング予約完了', amount: 25000, type: 'fixed' }],
    approvalRate: 62,
    epc: 110.5,
    itpSupport: true,
    cookieDuration: 45,
    isActive: true,
    recommendedAnchors: ['メンズエミナル 公式サイト', '低価格メンズ脱毛', '医療脱毛の無料カウンセリング'],
  },
  {
    id: 'at-skin-001',
    aspName: 'accesstrade',
    programName: 'オルビス Mr.',
    programId: 'at-prog-skin-001',
    category: 'skincare',
    rewardTiers: [{ condition: '初回購入完了', amount: 6000, type: 'fixed' }],
    approvalRate: 85,
    epc: 42.0,
    itpSupport: true,
    cookieDuration: 60,
    isActive: true,
    recommendedAnchors: ['オルビス Mr. 公式サイト', 'メンズ用スキンケア', '男性向け化粧水'],
  },
  {
    id: 'at-ed-001',
    aspName: 'accesstrade',
    programName: 'イースト駅前クリニック ED',
    programId: 'at-prog-ed-001',
    category: 'ed',
    rewardTiers: [{ condition: '初診予約完了', amount: 12000, type: 'fixed' }],
    approvalRate: 70,
    epc: 72.5,
    itpSupport: true,
    cookieDuration: 30,
    isActive: true,
    recommendedAnchors: ['イースト駅前クリニック', 'ED治療薬の処方', '駅前でED相談'],
  },

  // ── valuecommerce ──────────────────────────────────────
  {
    id: 'vc-aga-001',
    aspName: 'valuecommerce',
    programName: 'ウィルAGAクリニック',
    programId: 'vc-prog-aga-001',
    category: 'aga',
    rewardTiers: [{ condition: '無料診断予約完了', amount: 20000, type: 'fixed' }],
    approvalRate: 58,
    epc: 88.0,
    itpSupport: false,
    cookieDuration: 30,
    isActive: true,
    recommendedAnchors: ['ウィルAGAクリニック', 'オーダーメイドAGA治療', 'AGA治療の無料診断'],
  },
  {
    id: 'vc-hair-001',
    aspName: 'valuecommerce',
    programName: 'メンズじぶんクリニック',
    programId: 'vc-prog-hair-001',
    category: 'hair-removal',
    rewardTiers: [{ condition: '無料カウンセリング予約完了', amount: 22000, type: 'fixed' }],
    approvalRate: 64,
    epc: 98.2,
    itpSupport: false,
    cookieDuration: 30,
    isActive: true,
    recommendedAnchors: ['メンズじぶんクリニック', '全身脱毛プラン', 'メンズ脱毛を始める'],
  },
  {
    id: 'vc-skin-001',
    aspName: 'valuecommerce',
    programName: 'NULL スキンケアライン',
    programId: 'vc-prog-skin-001',
    category: 'skincare',
    rewardTiers: [{ condition: '初回購入完了', amount: 7000, type: 'fixed' }],
    approvalRate: 78,
    epc: 35.8,
    itpSupport: false,
    cookieDuration: 45,
    isActive: true,
    recommendedAnchors: ['NULL スキンケア', 'メンズBBクリーム', '男性用スキンケア'],
  },
  {
    id: 'vc-ed-001',
    aspName: 'valuecommerce',
    programName: 'フィットクリニック ED',
    programId: 'vc-prog-ed-001',
    category: 'ed',
    rewardTiers: [{ condition: '初診予約完了', amount: 9000, type: 'fixed' }],
    approvalRate: 74,
    epc: 50.3,
    itpSupport: false,
    cookieDuration: 30,
    isActive: true,
    recommendedAnchors: ['フィットクリニック ED治療', 'オンライン診療でED治療', 'ED薬を処方してもらう'],
  },

  // ── felmat ──────────────────────────────────────────────
  {
    id: 'fm-aga-001',
    aspName: 'felmat',
    programName: 'B&Hメディカルクリニック AGA',
    programId: 'fm-prog-aga-001',
    category: 'aga',
    rewardTiers: [{ condition: '無料相談予約完了', amount: 25000, type: 'fixed' }],
    approvalRate: 55,
    epc: 102.0,
    itpSupport: true,
    cookieDuration: 60,
    isActive: true,
    recommendedAnchors: ['B&Hメディカルクリニック', 'AGA専門治療', '発毛治療の無料相談'],
  },
  {
    id: 'fm-hair-001',
    aspName: 'felmat',
    programName: 'ダビデクリニック メンズ脱毛',
    programId: 'fm-prog-hair-001',
    category: 'hair-removal',
    rewardTiers: [{ condition: '無料体験予約完了', amount: 30000, type: 'fixed' }],
    approvalRate: 52,
    epc: 120.0,
    itpSupport: true,
    cookieDuration: 60,
    isActive: true,
    recommendedAnchors: ['ダビデクリニック', '新宿メンズ脱毛', 'ヒゲ脱毛の無料体験'],
  },
  {
    id: 'fm-skin-001',
    aspName: 'felmat',
    programName: 'ZO SKIN HEALTH メンズ',
    programId: 'fm-prog-skin-001',
    category: 'skincare',
    rewardTiers: [{ condition: 'トライアルセット購入完了', amount: 10000, type: 'fixed' }],
    approvalRate: 70,
    epc: 52.0,
    itpSupport: true,
    cookieDuration: 45,
    isActive: true,
    recommendedAnchors: ['ZO SKIN HEALTH', 'ドクターズコスメ', 'メンズ美肌プログラム'],
  },
  {
    id: 'fm-ed-001',
    aspName: 'felmat',
    programName: 'メンズライフクリニック ED',
    programId: 'fm-prog-ed-001',
    category: 'ed',
    rewardTiers: [{ condition: '初診予約完了', amount: 15000, type: 'fixed' }],
    approvalRate: 66,
    epc: 78.0,
    itpSupport: true,
    cookieDuration: 45,
    isActive: true,
    recommendedAnchors: ['メンズライフクリニック', 'ED治療専門院', '男性機能の無料相談'],
  },

  // ── moshimo (もしもアフィリエイト — +12% W報酬) ───────────
  {
    id: 'moshimo-aga-001',
    aspName: 'moshimo',
    programName: 'Amazon AGA関連商品',
    programId: 'moshimo-prog-aga-001',
    category: 'aga',
    rewardTiers: [{ condition: '商品購入完了 (W報酬+12%)', amount: 0, type: 'percentage' }],
    approvalRate: 90,
    epc: 25.0,
    itpSupport: true,
    cookieDuration: 24,
    isActive: true,
    recommendedAnchors: ['育毛剤をAmazonで探す', 'AGA関連商品一覧', 'Amazonで購入する'],
  },
  {
    id: 'moshimo-hair-001',
    aspName: 'moshimo',
    programName: 'Amazon 脱毛関連商品',
    programId: 'moshimo-prog-hair-001',
    category: 'hair-removal',
    rewardTiers: [{ condition: '商品購入完了 (W報酬+12%)', amount: 0, type: 'percentage' }],
    approvalRate: 90,
    epc: 22.0,
    itpSupport: true,
    cookieDuration: 24,
    isActive: true,
    recommendedAnchors: ['脱毛グッズをAmazonで探す', '家庭用脱毛器一覧', 'Amazonで購入する'],
  },
  {
    id: 'moshimo-skin-001',
    aspName: 'moshimo',
    programName: '楽天 メンズスキンケア',
    programId: 'moshimo-prog-skin-001',
    category: 'skincare',
    rewardTiers: [{ condition: '商品購入完了 (W報酬+12%)', amount: 0, type: 'percentage' }],
    approvalRate: 88,
    epc: 18.5,
    itpSupport: true,
    cookieDuration: 24,
    isActive: true,
    recommendedAnchors: ['楽天でスキンケア商品を探す', 'メンズ化粧品ランキング', '楽天で購入する'],
  },
  {
    id: 'moshimo-ed-001',
    aspName: 'moshimo',
    programName: 'Amazon ED関連サプリ',
    programId: 'moshimo-prog-ed-001',
    category: 'ed',
    rewardTiers: [{ condition: '商品購入完了 (W報酬+12%)', amount: 0, type: 'percentage' }],
    approvalRate: 85,
    epc: 20.0,
    itpSupport: true,
    cookieDuration: 24,
    isActive: true,
    recommendedAnchors: ['Amazonでサプリを探す', '活力サプリメント一覧', 'Amazonで購入する'],
  },
]

// ============================================================
// クエリ関数
// ============================================================

/**
 * 全ASPプログラムを取得する
 */
export function getPrograms(): AspProgram[] {
  return ASP_PROGRAMS.filter((p) => p.isActive)
}

/**
 * カテゴリ別にASPプログラムを取得する
 */
export function getProgramsByCategory(category: ContentCategory): AspProgram[] {
  return ASP_PROGRAMS.filter((p) => p.isActive && p.category === category)
}

/**
 * ASP名別にプログラムを取得する
 */
export function getProgramsByAsp(aspName: AspName): AspProgram[] {
  return ASP_PROGRAMS.filter((p) => p.isActive && p.aspName === aspName)
}
