/**
 * ASPプログラム設定
 * 5 ASP x 4 カテゴリ = 20 プログラム定義
 */

import type { AspProgram, AspName } from '@/types/asp-config'
import type { ContentCategory } from '@/types/content'

// ============================================================
// ASPプログラム一覧 (20エントリ)
// ============================================================

export const ASP_PROGRAMS: AspProgram[] = [
  // ── afb ──────────────────────────────────────────────
  {
    id: 'afb-aga-001',
    aspName: 'afb',
    programName: 'AGAスキンクリニック',
    programId: 'afb-prog-aga-001',
    category: 'aga',
    affiliateUrl: 'https://t.afi-b.com/visit.php?guid=ON&a=aga-skin-001',
    rewardAmount: 15000,
    rewardType: 'fixed',
    approvalRate: 72,
    epc: 85.5,
    itpSupport: true,
    cookieDuration: 60,
    isActive: true,
    recommendedAnchors: ['AGAスキンクリニック 公式サイト', 'AGA治療の無料カウンセリング', 'AGA治療を始める'],
    landingPageUrl: 'https://www.agaskin.net/',
  },
  {
    id: 'afb-hair-001',
    aspName: 'afb',
    programName: 'メンズリゼクリニック',
    programId: 'afb-prog-hair-001',
    category: 'hair-removal',
    affiliateUrl: 'https://t.afi-b.com/visit.php?guid=ON&a=mens-rize-001',
    rewardAmount: 20000,
    rewardType: 'fixed',
    approvalRate: 68,
    epc: 92.3,
    itpSupport: true,
    cookieDuration: 60,
    isActive: true,
    recommendedAnchors: ['メンズリゼ 公式サイト', 'メンズ脱毛の無料カウンセリング', '医療脱毛を始める'],
    landingPageUrl: 'https://www.mens-rize.com/',
  },
  {
    id: 'afb-skin-001',
    aspName: 'afb',
    programName: 'ゴリラクリニック スキンケア',
    programId: 'afb-prog-skin-001',
    category: 'skincare',
    affiliateUrl: 'https://t.afi-b.com/visit.php?guid=ON&a=gorilla-skin-001',
    rewardAmount: 8000,
    rewardType: 'fixed',
    approvalRate: 75,
    epc: 45.2,
    itpSupport: true,
    cookieDuration: 45,
    isActive: true,
    recommendedAnchors: ['ゴリラクリニック スキンケア', 'メンズ美肌治療', '肌悩みを相談する'],
    landingPageUrl: 'https://gorilla.clinic/skin/',
  },
  {
    id: 'afb-ed-001',
    aspName: 'afb',
    programName: 'クリニックフォア ED',
    programId: 'afb-prog-ed-001',
    category: 'ed',
    affiliateUrl: 'https://t.afi-b.com/visit.php?guid=ON&a=clinicfor-ed-001',
    rewardAmount: 10000,
    rewardType: 'fixed',
    approvalRate: 80,
    epc: 62.8,
    itpSupport: true,
    cookieDuration: 30,
    isActive: true,
    recommendedAnchors: ['クリニックフォア ED治療', 'オンラインED診療', 'ED治療の相談をする'],
    landingPageUrl: 'https://www.clinicfor.life/ed/',
  },

  // ── a8 ──────────────────────────────────────────────
  {
    id: 'a8-aga-001',
    aspName: 'a8',
    programName: 'Dクリニック',
    programId: 'a8-prog-aga-001',
    category: 'aga',
    affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=aga-dclinic-001',
    rewardAmount: 12000,
    rewardType: 'fixed',
    approvalRate: 65,
    epc: 70.2,
    itpSupport: false,
    cookieDuration: 30,
    isActive: true,
    recommendedAnchors: ['Dクリニック 公式サイト', '薄毛治療の専門医に相談', 'AGA治療実績No.1クリニック'],
    landingPageUrl: 'https://www.d-clinic.net/',
  },
  {
    id: 'a8-hair-001',
    aspName: 'a8',
    programName: 'レジーナクリニック オム',
    programId: 'a8-prog-hair-001',
    category: 'hair-removal',
    affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=regina-homme-001',
    rewardAmount: 18000,
    rewardType: 'fixed',
    approvalRate: 70,
    epc: 78.6,
    itpSupport: false,
    cookieDuration: 30,
    isActive: true,
    recommendedAnchors: ['レジーナクリニック オム', 'メンズ医療脱毛', '男性脱毛の相談をする'],
    landingPageUrl: 'https://reginaclinic.jp/homme/',
  },
  {
    id: 'a8-skin-001',
    aspName: 'a8',
    programName: 'メンズスキンケア BULK HOMME',
    programId: 'a8-prog-skin-001',
    category: 'skincare',
    affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=bulk-homme-001',
    rewardAmount: 5000,
    rewardType: 'fixed',
    approvalRate: 82,
    epc: 38.4,
    itpSupport: false,
    cookieDuration: 45,
    isActive: true,
    recommendedAnchors: ['BULK HOMME 公式サイト', 'メンズスキンケアを始める', '男性用基礎化粧品'],
    landingPageUrl: 'https://bulk.co.jp/',
  },
  {
    id: 'a8-ed-001',
    aspName: 'a8',
    programName: 'DMMオンラインクリニック ED',
    programId: 'a8-prog-ed-001',
    category: 'ed',
    affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=dmm-clinic-ed-001',
    rewardAmount: 8000,
    rewardType: 'fixed',
    approvalRate: 78,
    epc: 55.1,
    itpSupport: false,
    cookieDuration: 30,
    isActive: true,
    recommendedAnchors: ['DMMオンラインクリニック', 'オンラインED診療', 'ED薬のオンライン処方'],
    landingPageUrl: 'https://clinic.dmm.com/ed/',
  },

  // ── accesstrade ──────────────────────────────────────
  {
    id: 'at-aga-001',
    aspName: 'accesstrade',
    programName: '銀座総合美容クリニック AGA',
    programId: 'at-prog-aga-001',
    category: 'aga',
    affiliateUrl: 'https://h.accesstrade.net/sp/cc?rk=ginza-aga-001',
    rewardAmount: 18000,
    rewardType: 'fixed',
    approvalRate: 60,
    epc: 95.0,
    itpSupport: true,
    cookieDuration: 45,
    isActive: true,
    recommendedAnchors: ['銀座総合美容クリニック', 'AGA治療の専門院', '薄毛治療の無料相談'],
    landingPageUrl: 'https://www.gincli.jp/aga/',
  },
  {
    id: 'at-hair-001',
    aspName: 'accesstrade',
    programName: 'メンズエミナルクリニック',
    programId: 'at-prog-hair-001',
    category: 'hair-removal',
    affiliateUrl: 'https://h.accesstrade.net/sp/cc?rk=eminal-mens-001',
    rewardAmount: 25000,
    rewardType: 'fixed',
    approvalRate: 62,
    epc: 110.5,
    itpSupport: true,
    cookieDuration: 45,
    isActive: true,
    recommendedAnchors: ['メンズエミナル 公式サイト', '低価格メンズ脱毛', '医療脱毛の無料カウンセリング'],
    landingPageUrl: 'https://eminal-clinic.jp/mens/',
  },
  {
    id: 'at-skin-001',
    aspName: 'accesstrade',
    programName: 'オルビス Mr.',
    programId: 'at-prog-skin-001',
    category: 'skincare',
    affiliateUrl: 'https://h.accesstrade.net/sp/cc?rk=orbis-mr-001',
    rewardAmount: 6000,
    rewardType: 'fixed',
    approvalRate: 85,
    epc: 42.0,
    itpSupport: true,
    cookieDuration: 60,
    isActive: true,
    recommendedAnchors: ['オルビス Mr. 公式サイト', 'メンズ用スキンケア', '男性向け化粧水'],
    landingPageUrl: 'https://www.orbis.co.jp/mr/',
  },
  {
    id: 'at-ed-001',
    aspName: 'accesstrade',
    programName: 'イースト駅前クリニック ED',
    programId: 'at-prog-ed-001',
    category: 'ed',
    affiliateUrl: 'https://h.accesstrade.net/sp/cc?rk=east-ed-001',
    rewardAmount: 12000,
    rewardType: 'fixed',
    approvalRate: 70,
    epc: 72.5,
    itpSupport: true,
    cookieDuration: 30,
    isActive: true,
    recommendedAnchors: ['イースト駅前クリニック', 'ED治療薬の処方', '駅前でED相談'],
    landingPageUrl: 'https://www.eastcl.com/ed/',
  },

  // ── valuecommerce ──────────────────────────────────────
  {
    id: 'vc-aga-001',
    aspName: 'valuecommerce',
    programName: 'ウィルAGAクリニック',
    programId: 'vc-prog-aga-001',
    category: 'aga',
    affiliateUrl: 'https://ck.jp.ap.valuecommerce.com/servlet/referral?va=will-aga-001',
    rewardAmount: 20000,
    rewardType: 'fixed',
    approvalRate: 58,
    epc: 88.0,
    itpSupport: false,
    cookieDuration: 30,
    isActive: true,
    recommendedAnchors: ['ウィルAGAクリニック', 'オーダーメイドAGA治療', 'AGA治療の無料診断'],
    landingPageUrl: 'https://will-agaclinic.com/',
  },
  {
    id: 'vc-hair-001',
    aspName: 'valuecommerce',
    programName: 'メンズじぶんクリニック',
    programId: 'vc-prog-hair-001',
    category: 'hair-removal',
    affiliateUrl: 'https://ck.jp.ap.valuecommerce.com/servlet/referral?va=jibun-mens-001',
    rewardAmount: 22000,
    rewardType: 'fixed',
    approvalRate: 64,
    epc: 98.2,
    itpSupport: false,
    cookieDuration: 30,
    isActive: true,
    recommendedAnchors: ['メンズじぶんクリニック', '全身脱毛プラン', 'メンズ脱毛を始める'],
    landingPageUrl: 'https://jibun-clinic.com/mens/',
  },
  {
    id: 'vc-skin-001',
    aspName: 'valuecommerce',
    programName: 'NULL スキンケアライン',
    programId: 'vc-prog-skin-001',
    category: 'skincare',
    affiliateUrl: 'https://ck.jp.ap.valuecommerce.com/servlet/referral?va=null-skin-001',
    rewardAmount: 7000,
    rewardType: 'fixed',
    approvalRate: 78,
    epc: 35.8,
    itpSupport: false,
    cookieDuration: 45,
    isActive: true,
    recommendedAnchors: ['NULL スキンケア', 'メンズBBクリーム', '男性用スキンケア'],
    landingPageUrl: 'https://mens-null.net/',
  },
  {
    id: 'vc-ed-001',
    aspName: 'valuecommerce',
    programName: 'フィットクリニック ED',
    programId: 'vc-prog-ed-001',
    category: 'ed',
    affiliateUrl: 'https://ck.jp.ap.valuecommerce.com/servlet/referral?va=fit-ed-001',
    rewardAmount: 9000,
    rewardType: 'fixed',
    approvalRate: 74,
    epc: 50.3,
    itpSupport: false,
    cookieDuration: 30,
    isActive: true,
    recommendedAnchors: ['フィットクリニック ED治療', 'オンライン診療でED治療', 'ED薬を処方してもらう'],
    landingPageUrl: 'https://fit-clinic.jp/ed/',
  },

  // ── felmat ──────────────────────────────────────────────
  {
    id: 'fm-aga-001',
    aspName: 'felmat',
    programName: 'B&Hメディカルクリニック AGA',
    programId: 'fm-prog-aga-001',
    category: 'aga',
    affiliateUrl: 'https://www.felmat.net/fmcl?ak=bh-aga-001',
    rewardAmount: 25000,
    rewardType: 'fixed',
    approvalRate: 55,
    epc: 102.0,
    itpSupport: true,
    cookieDuration: 60,
    isActive: true,
    recommendedAnchors: ['B&Hメディカルクリニック', 'AGA専門治療', '発毛治療の無料相談'],
    landingPageUrl: 'https://www.bh-medical.jp/aga/',
  },
  {
    id: 'fm-hair-001',
    aspName: 'felmat',
    programName: 'ダビデクリニック メンズ脱毛',
    programId: 'fm-prog-hair-001',
    category: 'hair-removal',
    affiliateUrl: 'https://www.felmat.net/fmcl?ak=davide-hair-001',
    rewardAmount: 30000,
    rewardType: 'fixed',
    approvalRate: 52,
    epc: 120.0,
    itpSupport: true,
    cookieDuration: 60,
    isActive: true,
    recommendedAnchors: ['ダビデクリニック', '新宿メンズ脱毛', 'ヒゲ脱毛の無料体験'],
    landingPageUrl: 'https://davide-clinic.com/',
  },
  {
    id: 'fm-skin-001',
    aspName: 'felmat',
    programName: 'ZO SKIN HEALTH メンズ',
    programId: 'fm-prog-skin-001',
    category: 'skincare',
    affiliateUrl: 'https://www.felmat.net/fmcl?ak=zoskin-mens-001',
    rewardAmount: 10000,
    rewardType: 'fixed',
    approvalRate: 70,
    epc: 52.0,
    itpSupport: true,
    cookieDuration: 45,
    isActive: true,
    recommendedAnchors: ['ZO SKIN HEALTH', 'ドクターズコスメ', 'メンズ美肌プログラム'],
    landingPageUrl: 'https://www.cutera.jp/zo/',
  },
  {
    id: 'fm-ed-001',
    aspName: 'felmat',
    programName: 'メンズライフクリニック ED',
    programId: 'fm-prog-ed-001',
    category: 'ed',
    affiliateUrl: 'https://www.felmat.net/fmcl?ak=menslife-ed-001',
    rewardAmount: 15000,
    rewardType: 'fixed',
    approvalRate: 66,
    epc: 78.0,
    itpSupport: true,
    cookieDuration: 45,
    isActive: true,
    recommendedAnchors: ['メンズライフクリニック', 'ED治療専門院', '男性機能の無料相談'],
    landingPageUrl: 'https://www.mens-life-clinic.com/ed/',
  },
]

// ============================================================
// クエリ関数
// ============================================================

/**
 * 全ASPプログラムを取得する
 */
export function getPrograms(): AspProgram[] {
  return ASP_PROGRAMS.filter((p) => p.isActive)
}

/**
 * カテゴリ別にASPプログラムを取得する
 */
export function getProgramsByCategory(category: ContentCategory): AspProgram[] {
  return ASP_PROGRAMS.filter((p) => p.isActive && p.category === category)
}

/**
 * ASP名別にプログラムを取得する
 */
export function getProgramsByAsp(aspName: AspName): AspProgram[] {
  return ASP_PROGRAMS.filter((p) => p.isActive && p.aspName === aspName)
}
