/**
 * 30キーワードターゲット定義
 * バッチ記事生成用のキーワードリスト
 * AGA / ED / 脱毛 / スキンケア / 複合 各カテゴリ5件 + 複合10件 = 30件
 */

import type { KeywordTarget } from '@/types/batch-generation'

// ============================================================
// AGA (男性型脱毛症) キーワード × 5
// ============================================================

const AGA_KEYWORDS: KeywordTarget[] = [
  {
    id: 'kw-aga-001',
    keyword: 'AGA治療 費用 相場',
    subKeywords: ['AGA 月額', 'AGA 治療費 平均', 'プロペシア 価格', 'フィナステリド 費用'],
    category: 'aga',
    priority: 'high',
    searchVolume: 8100,
    difficulty: 45,
    targetAudience: 'AGA治療を検討中の20〜40代男性',
    tone: 'informative',
    targetLength: 4000,
    outlineHints: [
      'AGA治療の費用構成（初診・再診・薬代・検査）を明確に分類',
      'オンライン診療 vs 対面診療の費用差を比較',
      '主要クリニックの月額費用を表形式で比較',
      '保険適用の可否と自費診療の理由を解説',
    ],
  },
  {
    id: 'kw-aga-002',
    keyword: 'AGA クリニック おすすめ',
    subKeywords: ['AGA病院 選び方', 'AGAクリニック 比較', 'オンラインAGA', 'AGA専門医'],
    category: 'aga',
    priority: 'high',
    searchVolume: 12100,
    difficulty: 55,
    targetAudience: 'AGA治療クリニックを探している30〜50代男性',
    tone: 'comparison',
    targetLength: 5000,
    outlineHints: [
      'クリニック選びの5つの評価基準を提示',
      '主要AGAクリニックの特徴・費用・口コミを比較',
      'タイプ別おすすめ（コスパ重視・実績重視・オンライン重視）',
      '初回カウンセリングの流れを解説',
    ],
  },
  {
    id: 'kw-aga-003',
    keyword: 'フィナステリド 効果',
    subKeywords: ['プロペシア 効果', 'フィナステリド 期間', 'フィナステリド 副作用', 'DHT 抑制'],
    category: 'aga',
    priority: 'medium',
    searchVolume: 6600,
    difficulty: 40,
    targetAudience: 'フィナステリドの処方を検討している男性',
    tone: 'informative',
    targetLength: 3500,
    outlineHints: [
      'フィナステリドの作用メカニズム（5αリダクターゼ阻害）を解説',
      '臨床試験データに基づく効果の実績',
      '効果実感までの期間（3〜6ヶ月の目安）',
      '副作用とその頻度を正確に記載',
    ],
  },
  {
    id: 'kw-aga-004',
    keyword: 'ミノキシジル 副作用',
    subKeywords: ['ミノキシジル 危険性', 'ミノキシジル 初期脱毛', 'ミノキシジル 動悸', 'ミノキシジル 内服 リスク'],
    category: 'aga',
    priority: 'medium',
    searchVolume: 5400,
    difficulty: 35,
    targetAudience: 'ミノキシジルの使用を検討中またはすでに使用中の男性',
    tone: 'informative',
    targetLength: 3500,
    outlineHints: [
      '外用・内服それぞれの副作用を分類',
      '初期脱毛のメカニズムと期間',
      '医師への相談が必要な症状の目安',
      '安全な使用のための注意点',
    ],
  },
  {
    id: 'kw-aga-005',
    keyword: 'AGA オンライン診療',
    subKeywords: ['AGA 遠隔診療', 'AGA スマホ診察', 'AGA オンライン処方', 'AGA 在宅治療'],
    category: 'aga',
    priority: 'high',
    searchVolume: 4400,
    difficulty: 42,
    targetAudience: '通院が難しくオンライン診療を希望する20〜40代男性',
    tone: 'informative',
    targetLength: 3500,
    outlineHints: [
      'オンライン診療の流れ（予約→診察→処方→配送）',
      '対面診療との違い・メリット・デメリット',
      'オンライン対応クリニックの比較',
      '初めてのオンライン診療Q&A',
    ],
  },
]

// ============================================================
// ED (勃起不全) キーワード × 5
// ============================================================

const ED_KEYWORDS: KeywordTarget[] = [
  {
    id: 'kw-ed-001',
    keyword: 'ED治療 費用',
    subKeywords: ['ED 治療費 相場', 'バイアグラ 価格', 'ED 保険適用', 'ED薬 値段'],
    category: 'ed',
    priority: 'high',
    searchVolume: 6600,
    difficulty: 40,
    targetAudience: 'ED治療の費用が気になる30〜60代男性',
    tone: 'informative',
    targetLength: 4000,
    outlineHints: [
      '治療薬ごとの費用比較（先発品 vs ジェネリック）',
      '初診料・再診料・処方料の内訳',
      '保険適用の条件と自費診療の解説',
      'オンライン診療の費用メリット',
    ],
  },
  {
    id: 'kw-ed-002',
    keyword: 'ED クリニック 比較',
    subKeywords: ['ED病院 おすすめ', 'ED専門 クリニック', 'ED オンライン クリニック', 'ED治療 病院選び'],
    category: 'ed',
    priority: 'high',
    searchVolume: 5400,
    difficulty: 48,
    targetAudience: 'ED治療クリニックを探している男性',
    tone: 'comparison',
    targetLength: 4500,
    outlineHints: [
      'ED治療クリニックの選び方5つのポイント',
      '主要クリニックの比較表（費用・薬の種類・プライバシー配慮）',
      'オンライン診療 vs 対面のメリット・デメリット',
      '初回受診の流れとFAQ',
    ],
  },
  {
    id: 'kw-ed-003',
    keyword: 'シルデナフィル ジェネリック',
    subKeywords: ['バイアグラ ジェネリック', 'シルデナフィル 価格', 'シルデナフィル 効果', 'ジェネリックED薬'],
    category: 'ed',
    priority: 'medium',
    searchVolume: 4400,
    difficulty: 35,
    targetAudience: 'ED治療薬のジェネリックを検討している男性',
    tone: 'informative',
    targetLength: 3500,
    outlineHints: [
      'シルデナフィルの基本情報と作用メカニズム',
      'ジェネリック品と先発品の違い',
      '服用方法と注意点',
      '副作用と禁忌事項',
    ],
  },
  {
    id: 'kw-ed-004',
    keyword: 'ED オンライン診療',
    subKeywords: ['ED スマホ診療', 'ED 遠隔診察', 'ED薬 オンライン処方', 'ED 在宅'],
    category: 'ed',
    priority: 'high',
    searchVolume: 3600,
    difficulty: 38,
    targetAudience: '対面受診に抵抗がありオンライン診療を希望する男性',
    tone: 'informative',
    targetLength: 3500,
    outlineHints: [
      'オンライン診療の利用手順',
      'プライバシーへの配慮ポイント',
      '処方可能な薬の種類',
      'オンライン診療対応クリニック一覧',
    ],
  },
  {
    id: 'kw-ed-005',
    keyword: 'ED 治療薬 種類',
    subKeywords: ['ED薬 比較', 'バイアグラ シアリス 違い', 'タダラフィル 効果', 'レビトラ 特徴'],
    category: 'ed',
    priority: 'medium',
    searchVolume: 4400,
    difficulty: 38,
    targetAudience: 'ED治療薬の種類と違いを知りたい男性',
    tone: 'comparison',
    targetLength: 4000,
    outlineHints: [
      '3大ED治療薬（シルデナフィル・タダラフィル・バルデナフィル）の比較',
      '作用時間・食事の影響・副作用の違い',
      'ジェネリックの有無と価格差',
      '自分に合った薬の選び方',
    ],
  },
]

// ============================================================
// 脱毛 キーワード × 5
// ============================================================

const HAIR_REMOVAL_KEYWORDS: KeywordTarget[] = [
  {
    id: 'kw-hr-001',
    keyword: 'メンズ脱毛 おすすめ',
    subKeywords: ['男性 脱毛 人気', 'メンズ脱毛 ランキング', 'メンズ脱毛サロン', 'メンズ脱毛 初めて'],
    category: 'hair-removal',
    priority: 'high',
    searchVolume: 14800,
    difficulty: 58,
    targetAudience: 'メンズ脱毛を検討中の20〜30代男性',
    tone: 'comparison',
    targetLength: 5000,
    outlineHints: [
      '医療脱毛 vs エステ脱毛の違い',
      '部位別のおすすめクリニック・サロン比較',
      '初回カウンセリングの流れ',
      '失敗しない選び方のポイント',
    ],
  },
  {
    id: 'kw-hr-002',
    keyword: 'ヒゲ脱毛 費用',
    subKeywords: ['ひげ脱毛 相場', 'ヒゲ脱毛 値段', 'ヒゲ脱毛 回数 費用', '髭脱毛 コスパ'],
    category: 'hair-removal',
    priority: 'high',
    searchVolume: 9900,
    difficulty: 50,
    targetAudience: 'ヒゲ脱毛の費用を知りたい20〜40代男性',
    tone: 'informative',
    targetLength: 4000,
    outlineHints: [
      '部位・回数別の費用目安表',
      '医療脱毛 vs エステ脱毛の費用比較',
      '主要クリニック・サロンの料金表',
      'コスパを高めるポイント',
    ],
  },
  {
    id: 'kw-hr-003',
    keyword: '医療脱毛 メンズ 全身',
    subKeywords: ['全身脱毛 メンズ 費用', '全身脱毛 メンズ 回数', '医療脱毛 全身 安い', 'メンズ全身脱毛 比較'],
    category: 'hair-removal',
    priority: 'medium',
    searchVolume: 5400,
    difficulty: 52,
    targetAudience: '全身脱毛を検討中の20〜30代男性',
    tone: 'comparison',
    targetLength: 4500,
    outlineHints: [
      '全身脱毛に含まれる部位の範囲',
      '必要回数と通院期間の目安',
      '主要クリニックの全身脱毛プラン比較',
      '痛み対策と施術の流れ',
    ],
  },
  {
    id: 'kw-hr-004',
    keyword: '脱毛クリニック 比較',
    subKeywords: ['脱毛クリニック 選び方', '医療脱毛 クリニック おすすめ', '脱毛 病院 比較', 'メンズ脱毛 クリニック'],
    category: 'hair-removal',
    priority: 'medium',
    searchVolume: 6600,
    difficulty: 55,
    targetAudience: '脱毛クリニック選びで迷っている男性',
    tone: 'comparison',
    targetLength: 5000,
    outlineHints: [
      '比較する評価基準の説明',
      '主要クリニック5〜8院の詳細比較',
      'レーザーの種類と機器の違い',
      'タイプ別おすすめクリニック',
    ],
  },
  {
    id: 'kw-hr-005',
    keyword: 'VIO脱毛 メンズ',
    subKeywords: ['メンズVIO 脱毛', 'VIO脱毛 男性 恥ずかしい', 'VIO脱毛 メンズ 痛み', 'メンズVIO 費用'],
    category: 'hair-removal',
    priority: 'medium',
    searchVolume: 4400,
    difficulty: 42,
    targetAudience: 'VIO脱毛に興味があるが不安を感じている男性',
    tone: 'friendly',
    targetLength: 3500,
    outlineHints: [
      'メンズVIO脱毛のメリットと衛生面の効果',
      '施術の流れとプライバシー配慮',
      '痛みの程度と軽減方法',
      '費用と回数の目安',
    ],
  },
]

// ============================================================
// スキンケア キーワード × 5
// ============================================================

const SKINCARE_KEYWORDS: KeywordTarget[] = [
  {
    id: 'kw-sc-001',
    keyword: 'メンズスキンケア 基本',
    subKeywords: ['メンズ スキンケア 順番', '男 スキンケア やり方', 'メンズスキンケア 初心者', '男性 洗顔 化粧水'],
    category: 'skincare',
    priority: 'high',
    searchVolume: 8100,
    difficulty: 38,
    targetAudience: 'スキンケアを始めたい20〜30代男性',
    tone: 'friendly',
    targetLength: 3500,
    outlineHints: [
      'スキンケアの基本ステップ（洗顔→化粧水→乳液）',
      '男性の肌の特徴と女性との違い',
      '肌質別のケアポイント',
      'おすすめのスターターセット',
    ],
  },
  {
    id: 'kw-sc-002',
    keyword: 'ニキビ跡 治療 メンズ',
    subKeywords: ['ニキビ跡 消す 方法', 'クレーター ニキビ跡', 'ニキビ跡 レーザー', 'ニキビ跡 皮膚科'],
    category: 'skincare',
    priority: 'medium',
    searchVolume: 5400,
    difficulty: 43,
    targetAudience: 'ニキビ跡に悩む20〜30代男性',
    tone: 'informative',
    targetLength: 4000,
    outlineHints: [
      'ニキビ跡の種類（赤み・色素沈着・クレーター）',
      'セルフケアと皮膚科治療の使い分け',
      '美容クリニックでの治療法と費用',
      '予防とアフターケア',
    ],
  },
  {
    id: 'kw-sc-003',
    keyword: 'シミ取り レーザー 費用',
    subKeywords: ['シミ レーザー 値段', 'シミ取り 皮膚科', 'シミ レーザー 効果', 'シミ治療 メンズ'],
    category: 'skincare',
    priority: 'medium',
    searchVolume: 4400,
    difficulty: 45,
    targetAudience: 'シミが気になり始めた30〜50代男性',
    tone: 'informative',
    targetLength: 3500,
    outlineHints: [
      'レーザー治療の種類と費用の目安',
      'クリニック選びのポイント',
      '施術の流れとダウンタイム',
      'シミ予防のスキンケア方法',
    ],
  },
  {
    id: 'kw-sc-004',
    keyword: '毛穴 ケア メンズ',
    subKeywords: ['毛穴 黒ずみ 男', '毛穴 開き 改善', '毛穴 スキンケア 男性', '鼻 毛穴 目立つ'],
    category: 'skincare',
    priority: 'low',
    searchVolume: 3600,
    difficulty: 32,
    targetAudience: '毛穴の悩みを改善したい20〜30代男性',
    tone: 'friendly',
    targetLength: 3000,
    outlineHints: [
      '毛穴が目立つ原因（皮脂・角栓・たるみ）',
      '自宅でできる毛穴ケア方法',
      'おすすめのスキンケアアイテム',
      'クリニックでの毛穴治療',
    ],
  },
  {
    id: 'kw-sc-005',
    keyword: 'メンズ化粧水 おすすめ',
    subKeywords: ['メンズ 化粧水 ランキング', '男性 化粧水 人気', 'メンズ化粧水 コスパ', '乾燥肌 化粧水 メンズ'],
    category: 'skincare',
    priority: 'high',
    searchVolume: 9900,
    difficulty: 48,
    targetAudience: '化粧水を選んでいる20〜40代男性',
    tone: 'comparison',
    targetLength: 4500,
    outlineHints: [
      '肌質別の化粧水選びガイド',
      'おすすめメンズ化粧水の比較',
      '正しい使い方と塗り方',
      '価格帯別のおすすめ',
    ],
  },
]

// ============================================================
// 複合 キーワード × 10
// ============================================================

const COMPOSITE_KEYWORDS: KeywordTarget[] = [
  {
    id: 'kw-cp-001',
    keyword: 'AGA治療 20代',
    subKeywords: ['若ハゲ 治療', '20代 薄毛 AGA', 'AGA 若い', '20代 抜け毛 対策'],
    category: 'aga',
    priority: 'high',
    searchVolume: 4400,
    difficulty: 38,
    targetAudience: '薄毛に悩み始めた20代前半〜後半の男性',
    tone: 'friendly',
    targetLength: 3500,
    outlineHints: [
      '20代でAGAになるメカニズム',
      '早期治療のメリット',
      '20代向けのクリニック・治療法',
      '費用負担を抑える方法',
    ],
  },
  {
    id: 'kw-cp-002',
    keyword: 'メンズ美容 クリニック 選び方',
    subKeywords: ['美容クリニック メンズ', 'メンズ美容 病院', '男性 美容医療 初めて', '美容外科 メンズ'],
    category: 'skincare',
    priority: 'medium',
    searchVolume: 3600,
    difficulty: 40,
    targetAudience: '美容クリニックの受診を検討中の20〜40代男性',
    tone: 'informative',
    targetLength: 4000,
    outlineHints: [
      '美容クリニックで受けられる施術一覧',
      '信頼できるクリニックの見分け方',
      'カウンセリングの流れと注意点',
      '費用の目安とカテゴリ別ガイド',
    ],
  },
  {
    id: 'kw-cp-003',
    keyword: '男性 薄毛 対策',
    subKeywords: ['薄毛 予防', '抜け毛 対策 男', 'ハゲ 防止', '薄毛 改善 方法'],
    category: 'aga',
    priority: 'high',
    searchVolume: 8100,
    difficulty: 42,
    targetAudience: '薄毛予防・改善策を探している男性全般',
    tone: 'informative',
    targetLength: 4000,
    outlineHints: [
      '薄毛の主な原因（AGA・生活習慣・ストレス）',
      '自宅でできる対策（シャンプー・頭皮ケア・食事）',
      '医療機関での治療法',
      '対策別の効果と期間の目安',
    ],
  },
  {
    id: 'kw-cp-004',
    keyword: 'メンズ脱毛 痛み',
    subKeywords: ['脱毛 痛い', '医療脱毛 痛み 男', 'ヒゲ脱毛 痛み', '脱毛 麻酔'],
    category: 'hair-removal',
    priority: 'medium',
    searchVolume: 3600,
    difficulty: 30,
    targetAudience: '脱毛の痛みが不安な男性',
    tone: 'friendly',
    targetLength: 3000,
    outlineHints: [
      '部位別の痛みの程度と体験談',
      'レーザーの種類による痛みの違い',
      '痛み軽減方法（麻酔クリーム・冷却・蓄熱式）',
      '痛みに配慮したクリニック選び',
    ],
  },
  {
    id: 'kw-cp-005',
    keyword: 'ED 若い人',
    subKeywords: ['20代 ED', '30代 ED', '若年性ED', 'ED 原因 若い'],
    category: 'ed',
    priority: 'medium',
    searchVolume: 3600,
    difficulty: 32,
    targetAudience: 'EDの悩みを抱える20〜30代の若年男性',
    tone: 'friendly',
    targetLength: 3500,
    outlineHints: [
      '若年層のEDの主な原因（心因性・生活習慣）',
      '受診のタイミングと恥ずかしさへの対処',
      '若年層向けの治療法と選択肢',
      '生活習慣改善のポイント',
    ],
  },
  {
    id: 'kw-cp-006',
    keyword: 'メンズ美容医療 初めて',
    subKeywords: ['美容医療 初心者 男性', 'メンズ美容 始め方', '美容クリニック 男 初めて', 'メンズ 美容施術'],
    category: 'skincare',
    priority: 'medium',
    searchVolume: 2900,
    difficulty: 28,
    targetAudience: '美容医療に初めて興味を持った20〜30代男性',
    tone: 'friendly',
    targetLength: 3500,
    outlineHints: [
      '初心者におすすめの施術ジャンル',
      '初めてのカウンセリングの流れ',
      '費用感と予算の目安',
      '施術前後の注意事項',
    ],
  },
  {
    id: 'kw-cp-007',
    keyword: 'AGA 初期症状',
    subKeywords: ['AGA セルフチェック', 'ハゲ 初期', '薄毛 初期サイン', 'AGA 見分け方'],
    category: 'aga',
    priority: 'medium',
    searchVolume: 5400,
    difficulty: 35,
    targetAudience: '自分がAGAかどうか気になっている男性',
    tone: 'informative',
    targetLength: 3000,
    outlineHints: [
      'AGAの初期症状チェックリスト',
      'AGA以外の脱毛症との違い',
      'セルフチェック方法',
      '受診のタイミングと早期治療の重要性',
    ],
  },
  {
    id: 'kw-cp-008',
    keyword: '医療脱毛 回数 メンズ',
    subKeywords: ['脱毛 何回 メンズ', '医療脱毛 回数 目安', 'ヒゲ脱毛 回数', '全身脱毛 回数 男'],
    category: 'hair-removal',
    priority: 'medium',
    searchVolume: 4400,
    difficulty: 38,
    targetAudience: '脱毛に必要な回数と期間を知りたい男性',
    tone: 'informative',
    targetLength: 3500,
    outlineHints: [
      '部位別の必要回数の目安',
      '毛周期と回数の関係',
      '回数を減らすためのポイント',
      '通院間隔とスケジュール例',
    ],
  },
  {
    id: 'kw-cp-009',
    keyword: 'メンズ スキンケア 30代',
    subKeywords: ['30代 スキンケア 男', '30代 肌 悩み 男性', 'エイジングケア メンズ', '30代 化粧水 メンズ'],
    category: 'skincare',
    priority: 'medium',
    searchVolume: 3600,
    difficulty: 35,
    targetAudience: '肌の変化を感じ始めた30代男性',
    tone: 'friendly',
    targetLength: 3500,
    outlineHints: [
      '30代で変わる肌の特徴',
      '30代向けスキンケアの基本ステップ',
      'エイジングケアのポイント',
      '30代向けおすすめアイテム',
    ],
  },
  {
    id: 'kw-cp-010',
    keyword: 'ED治療 保険適用',
    subKeywords: ['ED 保険 きく', 'ED治療 自費', 'ED 医療費控除', 'バイアグラ 保険'],
    category: 'ed',
    priority: 'medium',
    searchVolume: 3600,
    difficulty: 30,
    targetAudience: 'ED治療の費用負担が気になる男性',
    tone: 'informative',
    targetLength: 3000,
    outlineHints: [
      'ED治療の保険適用範囲（2022年4月の変更点）',
      '保険適用の条件と対象薬剤',
      '自費診療の費用目安',
      '費用を抑えるための方法',
    ],
  },
]

// ============================================================
// エクスポート
// ============================================================

/**
 * 全30キーワードターゲットリスト
 */
export const KEYWORD_TARGETS: KeywordTarget[] = [
  ...AGA_KEYWORDS,
  ...ED_KEYWORDS,
  ...HAIR_REMOVAL_KEYWORDS,
  ...SKINCARE_KEYWORDS,
  ...COMPOSITE_KEYWORDS,
]
